flake.lock, flake.nix, modules/nixos.nix, modules/programs/alacritty.nix, modules/programs/default.nix
I think we have a decent base to work with here. It would be very nice to add tests for each module in the future, but I'm not going to bother with those for a year (hah.)
Quick PR to get rid of some footguns ([don't import NixOS modules](https://fzakaria.com/2024/07/29/import-but-don-t-import-your-nixos-modules.html)] and the lack of a vendored flake.lock as well as to organize lib inherits, and remove redundant expressions.
=> nix: general cleanup

flake.nix, modules/nixos.nix, modules/programs/default.nix
Created a function that creates a list of all the modules inside the programs folder. If other folders are used in the future, this function can be easily modified to be applied to each folder by mapping it.
Basically, this function reads the directory, filters all files that are "regular", picks their names (paths) and puts the parent directory in the path. When/if the pipe operator becomes stable we can use it instead of lib.pipe, making it cleaner.
Removed the programs/default.nix, as it isn't necessary anymore. Also, modified the module call in flake.nix to handle a function that receives a lib argument, as nixpkgs' lib is necessary.
=> nixosModules: autogenerate list of modules

flake.nix, modules/lib/default.nix, modules/lib/generators.nix
Inits the skeleton for extending lib. Doesn't yet add any custom functions, but this allows for contributors to easily extend lib for modules.
@PolarFill, go ahead and add any functions you need. I would prefer to merge this with at least one function added and used as a proof-of-concept.
=> Init lib extending

modules/programs/alacritty.nix, modules/programs/spotify-player.nix, modules/programs/vscode.nix
This simple PR adds conditional logic to file generation so that they are only created and symlinked if the config has actually been changed.
In practice, this means there won't be empty files cluttering the store, and that a user does not need a `mkDefault` to change a file themself when using a certain module; i.e. if I am using the spotify-player module but wish to link `theme.toml` to a specific file, I can doso without the use of `mkDefault`.
=> collection: add logic for file generation only if not null

flake.lock, modules/nixos.nix
The extended library was previously not properly being imported into the extraModules due to the way it is setup. It is now properly passed through Hjem's `specialArgs` option and now is made available in modules.
@PolarFill if you can, try to rebase onto this PR to test it out.
=> nixos: properly pass the extended library into extraModules

modules/collection/programs/ghostty.nix
This PR adds support for [Ghostty](https://github.com/ghostty-org/ghostty) (a terminal emulator). Supports settings and theming.
=> ghostty: init module

modules/nixos.nix
This PR allows module writers to reference the system config with `osConfig`. Basically, all it is is an alias for `config` while the standard `config` is an alias for `config.hjem.users.<username>`.
=> nixos.nix: init osConfig specialArg

modules/collection/programs/tofi.nix, modules/lib/types/default.nix, modules/lib/types/tofiSettingsType.nix
This adds a module for [tofi](https://github.com/philj56/tofi)! :D
=> Add module for tofi

modules/collection/programs/ncmpcpp.nix, modules/lib/generators/default.nix, modules/lib/generators/ncmpcpp.nix, modules/lib/types/default.nix, modules/lib/types/ncmpcppBindingType.nix
Adds support for [ncmpcpp](https://github.com/ncmpcpp/ncmpcpp/) configuration via rum.
Currently, the bindings interface accepts lines instead of trying to convert an attrset, but an approach similar to the [hm module](https://github.com/nix-community/home-manager/blob/release-24.05/modules/programs/ncmpcpp.nix#L21) could be taken.
=> add ncmpcpp module

modules/collection/programs/hyprland.nix, modules/lib/attrsets/default.nix, modules/lib/attrsets/filterKeysPrefixes.nix, modules/lib/default.nix, modules/lib/generators/default.nix, modules/lib/generators/environment.nix, modules/lib/generators/hypr.nix, modules/lib/types/default.nix, modules/lib/types/hyprType.nix
This PR adds Hyprland support for hjem-rum. 
- Settings mapped to hyprlang
- Plugins (can either take in a path or a package)
- Automatic environment sourcing (using the user's NixOS config to determine whether or not UWSM is enabled and imports environment the proper way)
Note that the latter will need to be added once hjem gets support for environment variables (feel-co/hjem#16), hence the draft status of this PR.
=> hyprland: init module

modules/collection/misc/gtk.nix, modules/lib/attrsets/attrNamesHasPrefix.nix, modules/lib/attrsets/default.nix
I moved the `attrsHasPrefix` function over into `lib/attrsets` to fit the new structure. I also took the liberty of renaming it to `attrNamesHasPrefix` to more accurately fit what the function does. After all, it literally is just a combination of `attrNames` and `hasPrefix`, so it seems more fitting. Plus, because it only checks the names, this seems more clear.
=> GTK: Cleanup 'attrsHasPrefix' function

modules/collection/programs/starship.nix
This PR adds a [Starship](https://starship.rs/) module.  Please keep in mind that shell support will need to be added once we get them into hjr. As per discussing it with @Lunarnovaa, a possible API we could use for it is: 
```nix
options.programs.zsh = {
integrations.starship = mkOption {
default = programs.starship.enable;
};
};
```
But this will do for now, since we do not have shells just yet.
=> starship: init module

modules/collection/programs/ghostty.nix, modules/collection/programs/vscode.nix
This PR brings the ghostty and vscode module to be more in line with the others, i.e. use `pkgs.formats` generators instead, which provide a very convenient type as well as a generate function, which we can directly set as the file source.
Please keep in mind that this brings slightly breaking changes for ghostty, as keybinds cannot be defined like this anymore:
```nix
keybind = {
"${prefix}>c" = "new_tab";
"${prefix}>p" = "move_tab:-1";
"${prefix}>n" = "move_tab:1";
};
```
But instead have to be defined as such (akin to home-manager): 
```nix
keybind = [
"${prefix}>c=new_tab"
"${prefix}>p=move_tab:-1"
"${prefix}>n=move_tab:1"
];
```
This will be the case for every nested key-value pairs.
PS: @Lunarnovaa since I do not use VSCode, could you please test it to see if it works as expected? …
=> modules/collection: migrate modules to `pkgs.formats`

modules/collection/programs/zsh.nix
This PR adds support for the zsh shell.
The plugins API is something I am not entirely sure about, and therefore would like input on it. I do not want us to add more opinionated options such as plugins specific options (akin to what home-manager does), because that would make for a convoluted API for something that the user can handle themselves.
Additionally, please let me know if the submodule could use a rewrite, or if any of the options feel like they do not belong here. You can see how I'm using it in my own configuration: https://github.com/nezia1/flocon/blob/2a75688309b991a386dec5130a7bfedf20fd8262/modules/programs/terminal/shell/zsh.nix
=> zsh: init module

flake.nix
Some changes got lost while I was manipulating the commit history, notably autoinstalling pre-commit when entering the shell. This aims to add it back.
=> meta: autoinstall pre-commit

modules/collection/programs/starship.nix
I don't know how I forgot to add it, but this was my fault. Starship was directly under `programs`, not `rum.programs`.
=> programs/starship: prefix starship under `rum`

modules/collection/programs/zsh.nix
Round 2 of me being forgetful. This fixes references I had not changed in zsh (the `integrations` option was using `config.programs.starship`). Apologies again.
=> programs/zsh: fix wrong references to starship

flake.nix
Simple thing I forgot to add, having our formatter in the devshell.
=> chore: add formatter to dev shell

modules/collection/programs/fish.nix
Initializes the fish module. I tried to strike a balance between not too much abstraction and ease of use.
Is an option to easily declare [abbreviations] something that would make sense ? Personally I'd think so.
[abbreviations]: https://nix-community.github.io/home-manager/options.xhtml#opt-programs.fish.shellAbbrs
=> fish: init module

.cz.toml, .pre-commit-config.yaml, README.md, docs/CONTRIBUTING.md, flake.nix
This PR adds linting to our commits through the means of [commitizen](https://github.com/commitizen-tools/commitizen/).
The format enforced can be found in `docs/CONTRIBUTING.md`:
```console
<scope>: <message>
<body>
```
=> Add commit message  hook

modules/collection/programs/fish.nix
Turns out documentation is helpful. The description ended up a bit more detailed, hope that its still fine
=> programs/fish: add description to plugins option

modules/collection/programs/starship.nix, modules/collection/programs/zsh.nix
As per what I talked about in #42. 
An important thing to take into consideration is that the global `integrations.enable` should be overrideable on a specific basis (if we want it for a specific shell and we might not want it for another, in the case of starship). The new architecture actually makes this trivial, as we can make the specific integrations take the value of `cfg.integrations.enable` by default.
We then only have to check for the value of the specific boolean, as `default` pretty much takes care of the logic for us, without convoluted boolean logic.
=> Move `zsh.integrations.starship` into `starship.integrations.zsh`

.cz.toml, docs/CONTRIBUTING.md
A simple fix, adding an optional body to our commit format. The docs have also been updated to reflect the new format.
=> meta/cz: add commit body; clarify questions

README.md, modules/collection/environment/warning.nix
Title. Basically, if users use a module that adds to sessionVariables (such as GTK) or simply add to it themselves (like for ozone), they may not know that it is not automatically loaded without the use of another module.
This has a very basic warning message so that users are aware at least. Once docs are in I would like to add a page on sessionVariables and direct users there for a warning.
There is also an option to disable the warning for users manually loading sessionVariables.
=> misc/environment: Add a warning for when sessionVariables exist but are not loaded by Hjem Rum

.pre-commit-config.yaml, README.md, docs/CONTRIBUTING.md, flake.lock, flake.nix
Title. This would be useful to have, as it makes `nix fmt` universally format everything nicely. It even provides its own dependencies under a devshell, that has also been added to our own. 
This is the reason why `python312Packages.mdformat` and `alejandra` were taken out of the `mkShell.packages`.
=> flake: add treefmt-nix

README.md, docs/CONTRIBUTING.md
This is a simple housekeeping PR, based on @nydragon's idea. GFM has supports for [reference links](https://github.github.com/gfm/#reference-link), which allows us to unclutter the main documentation file, and put all the links at the bottom of the file, in a centralized place.
=> docs/CONTRIBUTING: convert links to reference links

.github/workflows/manual.yml, docs/CONTRIBUTING.md, docs/manpage-urls.json, docs/package.nix, flake.lock, flake.nix, modules/collection/misc/gtk.nix, modules/collection/programs/alacritty.nix, modules/collection/programs/bottom.nix, modules/collection/programs/fish.nix, modules/collection/programs/foot.nix, modules/collection/programs/fuzzel.nix, modules/collection/programs/gammastep.nix, modules/collection/programs/ghostty.nix, modules/collection/programs/git.nix, modules/collection/programs/helix.nix, modules/collection/programs/hypridle.nix, modules/collection/programs/hyprland.nix, modules/collection/programs/hyprlock.nix, modules/collection/programs/keepassxc.nix, modules/collection/programs/lsd.nix, modules/collection/programs/ncmpcpp.nix, modules/collection/programs/obs-studio.nix, modules/collection/programs/spotify-player.nix, modules/collection/programs/starship.nix, modules/collection/programs/tofi.nix, modules/collection/programs/vscode.nix, modules/collection/programs/zsh.nix, modules/lib/generators/ncmpcpp.nix, modules/lib/types/hyprType.nix
This PR adds support for documentation through the means of [ndg v2](https://github.com/feel-co/ndg/tree/v2). This PR is a draft as I have not been able to figure out *yet* how to generate a proper optionsJSON, as some attributes seem to be missing for a proper evaluation: 
```console
error: attribute 'users' missing
at /nix/store/z7hkn7gh9xjx2m4kaxz3a5rwzpyr122x-source/modules/nixos/default.nix:27:25:
26|             user = config.users.users.${name}.name;
27|             directory = config.users.users.${name}.home;
|                         ^
28|             clobberFiles = cfg.clobberByDefault;
```
Unsure how I could remedy to this. @NotAShelf could you please take a look at this and tell me what I'm doing wrong?
=> Add documentation

modules/collection/programs/zoxide.nix, modules/tests/programs/zoxide.nix
I wasn't able to test this since I neither use zsh, nor fish and I'm too lazy to set them up right now. It evals, FWIW; please test.
=> programs/zoxide: init module

modules/collection/programs/fish.nix, modules/tests/programs/fish.nix
This adds an option to make aliases in fish. This can be useful as people often use aliases in shells and, in the future, it would be easier to integrate shell aliases or do something like `programs.fish.aliases = config.programs.othershell.aliases` and vice-versa.
=> programs/fish: add aliases option

modules/collection/programs/direnv.nix, modules/tests/programs/direnv/direnv.nix
Add nushell integration to direnv. I wanted to add it to fzf too, but it turns out it doesn't exist.
=> programs/direnv: add nushell integration

modules/collection/desktops/niri.nix
Added missing options descriptions to the niri module, and fixed a typo. Also uncapitalized niri because in their repo, it seems like they only capitalize it at beginning of sentences, so I thought it best to follow their conventions.
=> desktops/niri: add missing option descriptions; fix typos

README.md, flake.lock, modules/collection/desktops/hyprland.nix, modules/collection/misc/gtk.nix, modules/collection/programs/alacritty.nix, modules/collection/programs/beets.nix, modules/collection/programs/bottom.nix, modules/collection/programs/direnv.nix, modules/collection/programs/fish.nix, modules/collection/programs/flameshot.nix, modules/collection/programs/foot.nix, modules/collection/programs/fuzzel.nix, modules/collection/programs/gammastep.nix, modules/collection/programs/ghostty.nix, modules/collection/programs/git.nix, modules/collection/programs/helix.nix, modules/collection/programs/hypridle.nix, modules/collection/programs/hyprlock.nix, modules/collection/programs/keepassxc.nix, modules/collection/programs/kitty.nix, modules/collection/programs/lsd.nix, modules/collection/programs/ncmpcpp.nix, modules/collection/programs/nushell.nix, modules/collection/programs/spotify-player.nix, modules/collection/programs/starship.nix, modules/collection/programs/tealdeer.nix, modules/collection/programs/tofi.nix, modules/collection/programs/vscode.nix, modules/collection/programs/zoxide.nix
Title. This makes our modules respect `XDG_CONFIG_HOME` (see feel-co/hjem#45).
This introduces breaking changes, as older versions of hjem will not have `xdg.config.files` available, an admonition has been added to the README mentioning the pull request.
=> Migrate to xdg

README.md
Fix documentation link, protocol was missing.
Related Issue(s): #73 
- There is a conflicting PR (#115), but considering the link has been broken since fcad99861c9f24f4c32ac7cae1f00d4b6fb9ba0c it might make sense to merge this PR
=> docs/website: fix documentation link
