modules/collection/programs/foot.nix
modules/collection/programs/keepassxc.nix

This PR adds 2 modules for configuring foot and keepassxc.
It also includes a way to set the configuration location.

Add module for foot and keepassxc

---

README.md

README.md: use new nug URL

---

README.md
docs/CONTRIBUTING.md

Sections that will likely be WIP when this is merged:
- Docs
- Tests
I am thinking those will be written in their respective PRs. I mainly wanted to get this done ASAP so that future work on CONTRIBUTING.md can be a more gradual process as opposed to one big PR. This was kind of exhausting to write as it is.
Please share any mistakes I made, disagreements you have, or structural changes you would like to see.

CONTRIBUTING.md: init

---

modules/collection/programs/ncmpcpp.nix
modules/lib/types/ncmpcppBindingType.nix

Formatted all non-formatted files.

chore: run nix fmt on all files

---

modules/collection/programs/git.nix

Add a module to configure git with.

git: add module

---

modules/collection/programs/helix.nix

helix: init module

---

modules/collection/programs/hyprlock.nix

Adding a hyprlock module to configure it with hjem-rum, also fixed formatting for helix.

Hyprlock add module

---

modules/collection/programs/helix.nix

quick pr to fix formatting issues in helix. hopefully this won't happen anymore with the pre-commit hook added.

helix: format

---

README.md

i forgot to commit this one before merging... my bad

readme: fix deprecation warning issue link

---

README.md

Small PR to add a warning to make potential users aware that Hjem is unfinished and that Hjem Rum may have bugs due to this. Also adds something about Home Manager.

docs/README: Add a warning about Hjem being unfinished.

---

modules/collection/programs/bottom.nix

Simple configuration based on TOML.

bottom: init module

---

modules/collection/programs/hypridle.nix

Just copied the hyprlock module and changed the mentions and the example.

hypridle: init module

---

modules/collection/programs/gammastep.nix

Simple module configured with INI.

gammastep: init module

---

modules/collection/programs/beets.nix
modules/tests/programs/beets/bad-settings.nix
modules/tests/programs/beets/beets.nix

Adding a module for configuring [beets].
[beets]: https://beets.io/

programs/beets: init module

---

modules/collection/programs/direnv.nix

Missed this in the original PR, sorry!

programs/direnv: fix bad examples

---

modules/collection/programs/alacritty.nix
modules/collection/programs/beets.nix
modules/collection/programs/bottom.nix
modules/collection/programs/direnv.nix
modules/collection/programs/fish.nix
modules/collection/programs/flameshot.nix
modules/collection/programs/foot.nix
modules/collection/programs/fuzzel.nix
modules/collection/programs/fzf.nix
modules/collection/programs/gammastep.nix
modules/collection/programs/ghostty.nix
modules/collection/programs/git.nix
modules/collection/programs/helix.nix
modules/collection/programs/hypridle.nix
modules/collection/programs/hyprlock.nix
modules/collection/programs/keepassxc.nix
modules/collection/programs/kitty.nix
modules/collection/programs/lsd.nix
modules/collection/programs/ncmpcpp.nix
modules/collection/programs/obs-studio.nix
modules/collection/programs/spotify-player.nix
modules/collection/programs/starship.nix
modules/collection/programs/tealdeer.nix
modules/collection/programs/tofi.nix
modules/collection/programs/vscode.nix
modules/collection/programs/zoxide.nix
modules/collection/programs/zsh.nix

Quick PR to make packages nullable, so the user can choose not to add a package with the module.
[Please mention related issues if applicable]::
Related Issue(s): N/A
[We do not currently have a policy against AI-generated code, but we ask you to disclose the usage of AI for code generation]::

modules: init nullable packages

---

README.md
modules/collection/environment/warning.nix
modules/collection/programs/nushell.nix
modules/collection/programs/starship.nix
modules/tests/programs/nushell.nix

First test I've written so lmk if I'm making any rookie mistakes. I have tested the starship integration in my own config and it should work, but there's not yet any starship tests so I couldn't add one for the integration. If you would like me to add that I technically could, but tbh I just want to be free of nushell's hell.
Related Issue(s): #17

programs/nushell: init nushell

---

docs/CONTRIBUTING.md
docs/REVIEWING.md

To create a better contributor experience. Hopefully we can try to follow some of these practices in reviews of this! Some stylistic nitpicks are encouraged - I want this to be good, and I'm sure there are some better ways to phrase things.

docs: add REVIEWING.md

---

.github/pull_request_template.md

[This is a comment]::
[The body goes below]::
Running `nix fmt` here removes the comments too, not sure what to do here. Raising the PR anyway.
[Please mention related issues if applicable]::
[We do not currently have a policy against AI-generated code, but we ask you to disclose the usage of AI for code generation]::
AI used to generate code included in this PR?: Yes/No

meta/pr_template: format

---

modules/collection/programs/starship.nix

[This is a comment]::
[The body goes below]::
This PR changes the zsh integration, using the rum's option, remove unnecessary check of the shell (as config is only applied when the shell is enabled anyways) and adds fish integration, with optional transience. I don't know how to do this integration in nushell, although it has support for a transient prompt.
The fish integration needs https://github.com/snugnug/hjem-rum/pull/101 to be merged to work.
[Please mention related issues if applicable]::
[We do not currently have a policy against AI-generated code, but we ask you to disclose the usage of AI for code generation]::

programs/starship: refactor & add fish integration

---

.cz.toml
README.md
modules/collection/desktops/hyprland.nix
modules/collection/environment/warning.nix

modules/hyprland: move to desktops namespace
[Please mention related issues if applicable]::
Related Issue(s): None.
[We do not currently have a policy against AI-generated code, but we ask you to disclose the usage of AI for code generation]::

modules: move hyprland to desktops namespace

---

modules/collection/programs/fish.nix

programs/fish: remove unecessary .fish in the end

---

modules/tests/programs/ghostty.nix

This adds module tests for Ghostty. I'm unexperienced with testing, so please let me know if I made any blunders. Also unsure what else I could test

tests/ghostty: init test

---

modules/collection/programs/nix-your-shell.nix
modules/tests/programs/nix-your-shell.nix

Added the module, integrations with all the shells in hjem-rum and tests for these integrations.

programs/nix-your-shell: add module, integrations and tests

---

modules/collection/programs/zed.nix
modules/tests/programs/zed/javascript.json
modules/tests/programs/zed/keymap.json
modules/tests/programs/zed/my-cool-theme.json
modules/tests/programs/zed/settings.json
modules/tests/programs/zed/tasks.json
modules/tests/programs/zed/zed.nix

programs/zed: init module

---

modules/collection/desktops/niri.nix

Please write the content and purpose of your changes here.
Related Issue(s): N/A

desktops/niri: fix `configFile` example
